### ISSUE TITLE
`kubeflow-dashboard` channels `1.8/edge` and `latest/edge` is not functional when deployed with Juju 3.5

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kubeflow-dashboard-operator#188]
### Bug Description
Note: This behavior is seen with `1.8/edge` and `latest/edge`, but not `1.8/stable`.
This issue is blocking the CI of PR #https://github.com/canonical/dex-auth-operator/pull/187.
This came up during the CI updates to Juju 3.5, specifically in the dex-auth [integration CI](https://github.com/canonical/dex-auth-operator/actions/runs/9001108260/job/24731925230) where `test_login` is timing out to login to the dshboard.
When trying to access the dashboard from the browser, it's unsuccessful with this error shown:
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
```
the response status is `503 Service Unavailable` and the server is `istio-envoy`

Observing the `istio-ingerssgateway` workload logs:
```
[2024-05-09T10:48:49.956Z] "GET /?next=%2F HTTP/1.1" 503 UF,URX upstream_reset_before_response_started{connection_failure,delayed_connect_error:_111} - "delayed_connect_error:_111" 0 168 64 - "172.31.18.195" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/124.0.6367.155 Safari/537.36" "60b6e7d2-4ee7-461f-aef4-9d510109ccbf" "10.64.140.43.nip.io" "10.1.199.227:8082" outbound|8082||kubeflow-dashboard.kubeflow.svc.cluster.local - 10.1.199.236:8080 172.31.18.195:3212 - -
```
delayed connection error 111 typically means the application port is not open

and observing the `kubeflow-dashboard` workload logs:
```
2024-05-09T09:42:41.298Z [pebble] HTTP API server listening on ":38813".
2024-05-09T09:42:41.299Z [pebble] Started daemon.
2024-05-09T09:43:07.129Z [pebble] GET /v1/plan?format=yaml 230.782µs 200
2024-05-09T09:43:07.148Z [pebble] POST /v1/layers 291.684µs 200
2024-05-09T09:43:07.163Z [pebble] POST /v1/services 7.638296ms 202
2024-05-09T09:43:07.170Z [pebble] GET /v1/notices?timeout=30s 25.7898025s 200
2024-05-09T09:43:07.170Z [pebble] Service "serve" starting: /usr/bin/npm start
2024-05-09T09:43:07.646Z [serve] 
2024-05-09T09:43:07.646Z [serve] > kubeflow-centraldashboard@0.0.2 start
2024-05-09T09:43:07.646Z [serve] > npm run serve
2024-05-09T09:43:07.646Z [serve] 
2024-05-09T09:43:08.112Z [serve] glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
2024-05-09T09:43:08.112Z [serve]   errno: -13,
2024-05-09T09:43:08.112Z [serve]   code: 'EACCES',
2024-05-09T09:43:08.112Z [serve]   syscall: 'scandir',
2024-05-09T09:43:08.112Z [serve]   path: '/root/.npm/_logs'
2024-05-09T09:43:08.112Z [serve] }
2024-05-09T09:43:08.114Z [serve] npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
2024-05-09T09:43:08.114Z [serve] npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
2024-05-09T09:43:08.114Z [serve] npm WARN logfile   errno: -13,
2024-05-09T09:43:08.115Z [serve] npm WARN logfile   code: 'EACCES',
2024-05-09T09:43:08.115Z [serve] npm WARN logfile   syscall: 'scandir',
2024-05-09T09:43:08.115Z [serve] npm WARN logfile   path: '/root/.npm/_logs'
2024-05-09T09:43:08.115Z [serve] npm WARN logfile }
2024-05-09T09:43:08.118Z [serve] 
2024-05-09T09:43:08.118Z [serve] > kubeflow-centraldashboard@0.0.2 serve
2024-05-09T09:43:08.118Z [serve] > node dist/server.js
2024-05-09T09:43:08.118Z [serve] 
2024-05-09T09:43:08.177Z [pebble] GET /v1/changes/1/wait?timeout=4.000s 1.012609377s 200
2024-05-09T09:43:08.177Z [pebble] GET /v1/notices?after=2024-05-09T09%3A43%3A07.164028187Z&timeout=30s 1.006409154s 200
2024-05-09T09:43:08.896Z [serve] Initializing Kubernetes configuration
2024-05-09T09:43:08.904Z [serve] [SEVERE] unhandledRejection Error: EACCES: permission denied, open '/var/run/secrets/kubernetes.io/serviceaccount/token'
2024-05-09T09:43:08.904Z [serve]     at Object.openSync (fs.js:462:3)
2024-05-09T09:43:08.904Z [serve]     at Object.readFileSync (fs.js:364:35)
2024-05-09T09:43:08.904Z [serve]     at KubeConfig.loadFromCluster (/app/node_modules/@kubernetes/client-node/dist/config.js:137:27)
2024-05-09T09:43:08.904Z [serve]     at KubeConfig.loadFromDefault (/app/node_modules/@kubernetes/client-node/dist/config.js:173:18)
2024-05-09T09:43:08.904Z [serve]     at new KubernetesService (/app/dist/k8s_service.js:45:25)
2024-05-09T09:43:08.904Z [serve]     at /app/dist/server.js:46:28
2024-05-09T09:43:08.904Z [serve]     at Generator.next (<anonymous>)
2024-05-09T09:43:08.904Z [serve]     at /app/dist/server.js:8:71
2024-05-09T09:43:08.904Z [serve]     at new Promise (<anonymous>)
2024-05-09T09:43:08.904Z [serve]     at __awaiter (/app/dist/server.js:4:12) {
2024-05-09T09:43:08.904Z [serve]   errno: -13,
2024-05-09T09:43:08.904Z [serve]   syscall: 'open',
2024-05-09T09:43:08.904Z [serve]   code: 'EACCES',
2024-05-09T09:43:08.904Z [serve]   path: '/var/run/secrets/kubernetes.io/serviceaccount/token'
2024-05-09T09:43:08.904Z [serve] }
2024-05-09T09:43:08.946Z [pebble] Service "serve" stopped unexpectedly with code 0
2024-05-09T09:43:08.946Z [pebble] Service "serve" on-success action is "restart", waiting ~500ms before restart (backoff 1)
```
we can see that the npm server is not able start, and the pebble service is constantly restarting with permission denied errors to access the files:
* var/run/secrets/kubernetes.io/serviceaccount/token
* /root/.npm/_logs

The kubeflow dashboard is down in this case, but the charm status still shows up as `active`. This is problematic because the charm's state is not representative.

### To Reproduce

1. Deploy the following charms from latest/edge or corresponding 1.8/edge channels:
```
dex-auth 
istio-ingressgateway
istio-pilot
kubeflow-dashboard
kubeflow-profiles
oidc-gatekeeper
```
2.  try to access the dashboard by visiting the public-url

### Environment

juju 3.5/stable
microk8s 1.25-strict/stable

### Relevant Log Output

```shell
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
```

**Comment by NohaIhab** [comment]
To gather more information, I've tested:
* the `1.8/edge` dashboard charm on juju 3.1, and it was functioning correctly.
* the `1.8/stable` dashboard charm on juju 3.5, this also functioned correctly.

So this concludes that the `1.8/edge` charm has a diff from `1.8/stable` that makes break with juju 3.5 specifically.

It's worth noting that we are using the rock in `1.8/edge`, but not in `1.8/stable`.

The Juju 3.5 release notes include the change https://github.com/juju/juju/pull/17070, I'm curious if this has to do with the errors we're seeing, and relating to the [rock](https://github.com/canonical/kubeflow-rocks/blob/main/centraldashboard/rockcraft.yaml) that we are using.

**Comment by NohaIhab** [comment]
Comparing the pod definitions when deploying with 3.4 and 3.5, this security context is additional in 3.5:
```
  securityContext:
    fsGroup: 170
    supplementalGroups:
    - 170
```

**Comment by ca-scribner** [comment]
I can reproduce with:
* juju 3.5/stable
* microk8s 1.25-strict/stable
* deployed with:
```
juju deploy kubeflow-dashboard --channel 1.8/stable --trust
juju deploy kubeflow-profiles --channel 1.8/stable --trust
juju relate kubeflow-dashboard kubeflow-profiles
```

**Comment by ca-scribner** [comment]
I can also reproduce this behaviour directly using kubernetes and the rock [charmedkubeflow/kubeflow-central-dashboard](https://hub.docker.com/r/charmedkubeflow/kubeflow-central-dashboard/tags) (source [rockcraft.yaml](https://github.com/canonical/kubeflow-rocks/blob/main/centraldashboard/rockcraft.yaml)) by:
```
rockcraft pack
skopeo --insecure-policy copy oci-archive:kubeflow-central-dashboard_1.8_amd64.rock docker-daemon:centraldashboard:rock
docker save centraldashboard:rock > tempimage
microk8s ctr image import tempimage
rm tempimage
kubectl -f broken-dashboard-rock.yaml
```

where broken-dashboard-rock.yaml is:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubeflow-dashboard-with-security-context
spec:
  automountServiceAccountToken: true
  securityContext:
    fsGroup: 170
    supplementalGroups:
    - 170
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: kubeflow-dashboard
    image: centraldashboard:rock
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /charm/bin/pebble
      name: charm-data
      readOnly: true
      subPath: charm/bin/pebble
    - mountPath: /charm/container
      name: charm-data
      subPath: charm/containers/kubeflow-dashboard
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-b4hms
      readOnly: true
  volumes:
  - emptyDir: {}
    name: charm-data
  - name: kube-api-access-b4hms
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```
(note that I'm reusing the `ServiceAccount` that `juju` created above for kubeflow-dashboard)

This raises the same errors as @NohaIhab mention above.  If we remove the `securityContext`s, the app works as normal.   

Looking at the serviceaccount/token that npm reports we cannot access, we see that it is in group `170`
```
kubectl exec kubeflow-dashboard-with-security-context -- ls -l /var/run/secrets/kubernetes.io/serviceaccount/token
lrwxrwxrwx 1 root 170 12 May  9 17:51 /var/run/secrets/kubernetes.io/serviceaccount/token -> ..data/token
```

which makes sense because setting `Pod.spec.securityContext.fsGroup: 170` sets that all `volumeMounts` will be part of group `170`.

**Comment by ca-scribner** [comment]
Interestingly, if we do the same example as above but use upstream's image (`kubeflownotebookswg/centraldashboard:v1.8.0`), the dashboard starts successfully.  Summary of some attempts:

* `kubeflownotebookswg/centraldashboard:v1.8.0` with container `securityContext: {runAsGroup: 0; runAsUser: 0}`:
  * dashboard starts successfully (can access serviceaccount token)
  * `kubectl exec kubeflow-dashboard-with-pod-security-context-upstream-image -- whoami` shows `root`
  * `kubectl exec kubeflow-dashboard-with-pod-security-context-upstream-image -- groups` shows `root 170 ...` (some other groups)
* `kubeflownotebookswg/centraldashboard:v1.8.0` **without** container `securityContext`:
  * dashboard starts successfully (can access serviceaccount token)
  * `kubectl exec kubeflow-dashboard-with-pod-security-context-upstream-image -- whoami` shows `node` (which is expected because the upstream image sets `USER node`
  * `kubectl exec kubeflow-dashboard-with-pod-security-context-upstream-image -- groups` shows `node 170`

So for the above cases, whether the upstream image is executed as `root` or `node`, they both appear to have the group `170` added to their existing groups.  Strangly, typing `groups node` or `groups root` in those sessions **does not** show `170` in the list, making me think Kubernetes adds that group in somehow on the fly to the existing user.

Interestingly if I `kubectl exec` (which gives me the root user) or `runc exec -u 584792` (which gives me the rockcraft `_daemon_` user), and then type `groups`, I see `170` **is** in my current groups and I **can** view the serviceaccount token.  So somehow in these adhoc sessions, the users are being granted access to group `170` just like above for the upstream docker images.  

### A theory of what is going on ...

My guess at what happening is that we're hitting trouble because rocks run their services via `pebble`.  My guess is that the `pebble` entrypoint is likely getting the added group `170` like we see with the docker images, but that `pebble` does not pass this group down to the processes that it executes.  So when pebble runs our service using the `_daemon_` user, it **does not** have group `170` and thus cannot access the service token.  

### Next steps

* try doing security context with uid/gid 584792 (the same id that pebble executes our services with).  Does that allow our dashboard service to access the serviceaccount token?
* make a rock where pebble executes a script that reports some debug info, like `groups` and `whoami` just to see what it is running.  Could also do some `cat /var/run/secretss...` etc in that script to see what it says

**Comment by ca-scribner** [comment]
Tried deploying the rock pod with the following changes (full yaml given below):
* set `fsGroup=584792` (to match the `_daemon_` user pebble would use to execute services in the rock
* remove the container `securityContext` (it didn't matter whether it was there or not - I tried both and got the same result)

<details><summary> pod.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubeflow-dashboard-with-security-context-as-584792
spec:
  automountServiceAccountToken: true
  securityContext:
    fsGroup: 584792
    supplementalGroups:
    - 584792
  serviceAccount: kubeflow-dashboard
  serviceAccountName: kubeflow-dashboard
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: kubeflow-dashboard
    image: kubeflow-central-dashboard:1.8
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      runAsGroup: 584792
      runAsUser: 584792
    volumeMounts:
    - mountPath: /charm/bin/pebble
      name: charm-data
      readOnly: true
      subPath: charm/bin/pebble
    - mountPath: /charm/container
      name: charm-data
      subPath: charm/containers/kubeflow-dashboard
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-b4hms
      readOnly: true
  volumes:
  - emptyDir: {}
    name: charm-data
  - name: kube-api-access-b4hms
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

</details>

So I think this reinforces the theory above that kubernetes natively grants the fsGroup to the entrypoint's process, but pebble does not do the same for its children
